user_posts/main/forms.py
from wtforms import Form, TextField, IntegerField, TextAreaField, validators

class PostForm(Form):
    title = TextField('Title', [validators.Length(min=3,max=50)])
    rating = IntegerField('Rating')
    description = TextAreaField('Description', [validators.Length(min=3,max=50)])

user_posts/main/views.py
from flask import Blueprint, render_template, flash, redirect, session, request, url_for

from user_posts.data.models import Post, Author, db
from user_posts.main.forms import PostForm

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def index():
    return render_template("index.html")


@main.route('posts')
def display_posts():
    posts = [post for post in Post.query.all()]
    return render_template("posts.html", posts=posts)

@main.route('add_post', methods=['GET','POST'])
def add_post():
	try:
		form = PostForm(request.form)
		if request.method == 'POST' and form.validate():
			title = form.title.data
			rating = form.rating.data
			description = form.description.data
			author = Author.query.filter(Author.username == session['username']).first()
			post = Post(title=title,rating=rating,description=description,author=author)
			db.session.add(post)
			db.session.commit()
			flash('New post was added successfully')
			return redirect(url_for('main.display_posts'))
	except Exception as e:
		flash(e)
	return render_template('add_post.html', form=form)

@main.route('delete/<int:post_id>', methods=['GET', 'POST'])
def delete(post_id):
	post = Post.query.filter(Post.id == post_id).first()
	db.session.delete(post)
	db.session.commit()
	flash('Your post was successfully removed')
	return redirect(url_for('main.display_posts'))

user_posts/main/templates/add_post.html
{% extends "layout.html" %}

{% block container %}

<div class="container">
  <h2>Add new post</h2>
  {% if error %}
    <p class="error"><strong>Error:</strong> {{ error }}</p>
  {% endif %}
	  <br> 
	  {% from "_formhelpers.html" import render_field %}
		<form method="post" action="{{url_for('main.add_post')}}">
		  <dl>
				{{ render_field(form.title) }}
				{{ render_field(form.rating) }}
				{{ render_field(form.description) }}
		  </dl>
		  <p><input type="submit" value="Add post">
		</form>
	</div>

{% endblock %}

user_posts/main/templates/index.html
{% extends 'layout.html' %}

{% block container %}
  <div class="top-pad">
    <h3>Flask application is the easiest forever!</h3>
  </div>
{% endblock %}

user_posts/main/templates/posts.html
{% extends 'layout.html' %}

{% block container %}
  {% if session.logged_in %}
    <a class="btn btn-primary btn-fab btn-raised mdi-content-add" href="{{ url_for('main.add_post') }}" >Add a new post</a>
  {% endif %}
  <div class="top-pad">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>title</th>
          <th>author</th>
          <th>rating</th>
          <th>description</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for post in posts %}
        <tr>
          <td>{{post.title | upper}}</td>
          <td>{{post.author.username}}</td>
          <td>{{post.rating}}</td>
          <td>{{post.description}}</td>
          <td>
          {% if session.username == post.author.username %}
            <button type="button" class="close" aria-label="Close" data-id={{post.id}}><span aria-hidden="true">&times;</span></button>
          {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <script type="text/javascript">
    $(function(){
      $('button.close').on('click', function(){
        var $post_id = $(this).attr('data-id');
        $.ajax({
          type: 'GET',
          url: $SCRIPT_ROOT + '/delete/' + $post_id,
          success: function(){
              window.location.href = '/posts';
          }
        })
      })
    });
  </script>
{% endblock %}